CFLAGS += -g -Wno-deprecated-declarations -D__PROG_TYPES_COMPAT__
CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)
TARGET = sparrow
CONTIKI = ../../../..
UIP_CONF_IPV6 = 1

include $(CONTIKI)/Makefile.include
